### PR TITLE
Added the ability to control the position of the read more link using an optional link container.

### PR DESCRIPTION
**Pull request by aelin-reed**

### CODE REVIEW

**Comment by daniel-reed** [comment]
Sure thing! I've used the modifications on this page:
http://hertogfoundation.org/meet-our-alumni

**Comment by DivaVocals** [comment]
Question regarding this PR.. I am trying to use this on the categories descriptions on an ecommerce site.. What I want to be able to do is put the **"More.."** link inside the div that contains the category description. so that I can place it just below the description. You can see I have this working on my dev site: http://tlwtestsite(dot)tablelegworld(dot)com/Motorized-Table-Legs, but I do not like the **"More.."** link being outside the categories. (see the link I posted to see what I mean)

Will applying the changes in this PR will I be able to achieve what I am after??

**Comment by leecollings** [comment]
Hi Jed,

Is there any update on this getting into a new version? If it's what I believe it is, this will allow the user to place the readmore link anywhere they like, correct?

Please advise how I could get this incorporated into the current plugin, if it's nowhere near being released yet.

**Comment by leecollings** [comment]
Although the 'readmore' link is able to placed specifically, the cutoff height is stilla fixed amount, and can reveal more text / clip it off if the amount of text before the read more link differs.

Can the maxHeight be set dynamically according to where the read more link is?

**Comment by jedfoster** [comment]
Thank you, but this feature adds more complexity than I like. I think the use case falls outside the scope of this project.

**Pull request closed without merging**
