### PR TITLE
Add UMD support to plugin

### PR DESCRIPTION
**Pull request by joshua703**
This makes it easier to use various module loaders such as Browserify and Webpack.

RFCR @mattmattmatt

### CODE REVIEW

**Comment by mattmattmatt** [comment]
Looks good to me. :+1:

**Comment by darfink** [comment]
Any update on this?

**Comment by mattmattmatt** [comment]
@jedfoster Any thoughts?

**Comment by jedfoster** [comment]
Looks like a great addition, but I haven't had time to review yet.

**Comment by jedfoster** [comment]
Very nice! This will go out in the next release. Thanks!

**Pull request merged**
