### PR TITLE
insertBefore

### PR DESCRIPTION
**Pull request by ImmortalJoker**
Hey, I've added new feature which can helps someone working with your plugin

### CODE REVIEW

**Comment by jedfoster** [comment]
Can you please provide a description of your new feature? What does it do? What problem does it solve? What are the possible use cases?

There are so many white-space changes in this PR that I cannot see what you actually changed. Can you please clean that up? Most likely, your text editor or IDE automatically changed the spaces to tabs.

**Comment by ImmortalJoker** [comment]
Actualy I added a small description to README.md and example to the demo.html.
Oh sorry for that, yes it's my IDEA did it, sure ill clean this up.

**Comment by ImmortalJoker** [comment]
Ok, I pushed changes with more obviouse case to use.
So the 'insertBefore' option making plugin more flexable so users can put links to collapse/expand content before the content or after

**Comment by jedfoster** [comment]
This will be included in Readmore.js v3.

**Pull request closed without merging**
